language: node_js

node_js:
  - "4.0"
  - "5.0"
  - "stable"

sudo: required
addons:
  chrome: stable

script:
  - ./node_modules/.bin/eslint ./**/*.js
  - ./node_modules/.bin/karma start --single-run

after_script:
  - cat build/coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
